#-------------------------------------------------------------------
# Tomcat configuration
#-------------------------------------------------------------------

#*****************************************************************************#
# Endpoints for local development
host.service.domain=local.cxdev.me
host.service.backend.port=${tomcat.ssl.port}
host.service.frontend.port=4200

# Fake managed properties for CCv2 services
ccv2.services.api.url.0=https://${host.service.domain}:${host.service.backend.port}
ccv2.services.backgroundprocessing.url.0=https://${host.service.domain}:${host.service.backend.port}
ccv2.services.backoffice.url.0=https://${host.service.domain}:${host.service.backend.port}
ccv2.services.jsapps.url.0=https://${host.service.domain}:${host.service.frontend.port}

# Reconfigure Cors filter
corsfilter.default.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.acceleratorservices.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.assistedservicewebservices.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.commercewebservices.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.oauth2.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.permissionswebservices.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.personalizationwebservices.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}
corsfilter.resourceserver.allowedOrigins=${ccv2.services.api.url.0},${ccv2.services.jsapps.url.0}

# Keystore setup to avoid SSL errors
tomcat.ssl.keystore.path=${HYBRIS_CONFIG_DIR}/../../../certificates/local.cxdev.me.p12
tomcat.ssl.keystore.password=123456
tomcat.ssl.keystore.alias=local.cxdev.me

# Keystore setup for integrated solr server
solrserver.instances.default.ssl.keyStore=${tomcat.ssl.keystore.path}
solrserver.instances.default.ssl.keyStorePassword=${tomcat.ssl.keystore.password}

# Domain configuration for smart edit
smartedit.tomcat.hostname=local.cxdev.me

