#-------------------------------------------------------------------
# Tomcat configuration
#-------------------------------------------------------------------
host.service.backend=https://local.cxdev.me:${tomcat.ssl.port}/
host.service.frontend=https://local.cxdev.me:4200/

# Deactivate Cors filter
corsfilter.default.allowedOrigins=*
corsfilter.acceleratorservices.allowedOrigins=*
corsfilter.assistedservicewebservices.allowedOrigins=*
corsfilter.commercewebservices.allowedOrigins=*
corsfilter.oauth2.allowedOrigins=*
corsfilter.permissionswebservices.allowedOrigins=*
corsfilter.personalizationwebservices.allowedOrigins=*

# Keystore setup to avoid SSL errors
tomcat.ssl.keystore.path=${HYBRIS_CONFIG_DIR}/../../../certificates/local.cxdev.me.p12
tomcat.ssl.keystore.password=123456
tomcat.ssl.keystore.alias=local.cxdev.me

# Keystore setup for integrated solr server
solrserver.instances.default.ssl.keyStore=${tomcat.ssl.keystore.path}
solrserver.instances.default.ssl.keyStorePassword=${tomcat.ssl.keystore.password}

# Domain configuration for smart edit
smartedit.tomcat.hostname=local.cxdev.me
smartedit.ssl.validation.enabled=false

