#-------------------------------------------------------------------
# SSO Configuration (Backend)

# We recommend to use a single keystore for tomcat and SSO, therefore,
# Tomcat's settings (see below) will be reused in this configuration area
#
# To import the identity providers certificate into your keystore, use e.g.:
# keytool -import -alias provider -file identityProvider.cert -keystore local.sapcx.tools.p12 
#
sso.keystore.location=file:${tomcat.ssl.keystore.path}
sso.keystore.password=${tomcat.ssl.keystore.password}
sso.keystore.default.certificate.alias:${tomcat.ssl.keystore.alias}
sso.keystore.privatekey.alias=${tomcat.ssl.keystore.alias}
sso.keystore.privatekey.password=${tomcat.ssl.keystore.password}

# Backoffce SAML configuration
sso.legacy.endpoints.enabled=false
sso.cookie.name=LoginToken
sso.relyingPartyRegistration.registrationId=sso
sso.redirect.url=${ccv2.services.backoffice.url.0}
sso.entity.id=urn:backoffice:local:cxdev:me
sso.metadata.location=file:${HYBRIS_CONFIG_DIR}/../../../certificates/cxdev_eu_auth0_com-metadata.xml
sso.userid.attribute.key=emailAddress
sso.usergroup.attribute.key=userGroup
sso.firstname.attribute.key=firstName
sso.lastname.attribute.key=lastName

# Group Level mapping
sso.mapping.CXDEV_BACKOFFICE_ADMIN.usertype=Employee
sso.mapping.CXDEV_BACKOFFICE_ADMIN.groups=admingroup
sso.mapping.CXDEV_BACKOFFICE_CMSEDITOR.usertype=Employee
sso.mapping.CXDEV_BACKOFFICE_CMSEDITOR.groups=cmseditorgroup
sso.mapping.CXDEV_BACKOFFICE_CMSMANAGER.usertype=Employee
sso.mapping.CXDEV_BACKOFFICE_CMSMANAGER.groups=cmsmanagergroup
sso.mapping.CXDEV_BACKOFFICE_PIMEDITOR.usertype=Employee
sso.mapping.CXDEV_BACKOFFICE_PIMEDITOR.groups=producteditorgroup
sso.mapping.CXDEV_BACKOFFICE_PIMMANAGER.usertype=Employee
sso.mapping.CXDEV_BACKOFFICE_PIMMANAGER.groups=productmanagergroup

#-------------------------------------------------------------------
# SSO Configuration (Frontend)

# SSO filter settings
sapcxsinglesignon.filter.enabled=true
sapcxsinglesignon.filter.login.userClientId=default
sapcxsinglesignon.filter.login.tokenExpiration=600
sapcxsinglesignon.filter.idp.issuer=https://cxdev.eu.auth0.com/
sapcxsinglesignon.filter.idp.audience=${ccv2.services.api.url.0}/occ/v2/
sapcxsinglesignon.filter.idp.claim.id=email

# Auth0 settings
sapcxssoauth0.auth0.domain=cxdev.eu.auth0.com
sapcxssoauth0.auth0.auth.api.clientid=MoLPH2ukZD5Ai7XnRv8AdEojE7Vd5JhV
sapcxssoauth0.auth0.auth.api.clientsecret=lHy6YSKRuEDRwIzmqjF9synS20hvOKt3WEGwWuHPLGfeXm2lEwgFt9FuZcXSNebi
sapcxssoauth0.auth0.management.api.domain=cxdev.eu.auth0.com
sapcxssoauth0.auth0.management.api.audience=https://cxdev.eu.auth0.com/api/v2/
sapcxssoauth0.auth0.management.api.clientid=XvTX26IpdM5jlpS4OKpaUPn9n4LpjvbR
sapcxssoauth0.auth0.management.api.clientsecret=j4DoFB8tE6WrvLXERa1QjT4K--z1TlZOgkpnLqt2Lvg9R3CFl4TznNLk9WI-Kicg

sapcxssoauth0.auth0.customer.connection=Username-Password-Authentication
sapcxssoauth0.auth0.customer.role=
sapcxssoauth0.auth0.customer.idfield=username
sapcxssoauth0.auth0.customer.useblockedstatus=false
sapcxssoauth0.auth0.customer.requireemailverification=false
sapcxssoauth0.auth0.customer.requirepasswordverification=false

# User management settings
sapcxssoauth0.replication.enabled=false
sapcxssoauth0.replicate.creation.enabled=false
sapcxssoauth0.replicate.removal.enabled=false

# Sample Frontend Environment Configuration
sapcxenvconfig.environment.id=L1
sapcxenvconfig.environment.name=Local Development
sapcxenvconfig.frontend.backend.occ.baseUrl=${ccv2.services.api.url.0}
sapcxenvconfig.frontend.authentication.client_id=${sapcxssoauth0.auth0.auth.api.clientid}
sapcxenvconfig.frontend.authentication.client_secret=${sapcxssoauth0.auth0.auth.api.clientsecret}
sapcxenvconfig.frontend.authentication.baseUrl=https://cxdev.eu.auth0.com
sapcxenvconfig.frontend.authentication.tokenEndpoint=/oauth/token
sapcxenvconfig.frontend.authentication.loginUrl=/authorize
sapcxenvconfig.frontend.authentication.revokeEndpoint=/oauth/revoke
sapcxenvconfig.frontend.authentication.logoutUrl=/oidc/logout
sapcxenvconfig.frontend.authentication.userinfoEndpoint=/userinfo
sapcxenvconfig.frontend.authentication.OAuthLibConfig.redirectUri=${ccv2.services.jsapps.url.0}
sapcxenvconfig.frontend.authentication.OAuthLibConfig.responseType=code
sapcxenvconfig.frontend.authentication.OAuthLibConfig.scope=openid profile email hybris
sapcxenvconfig.frontend.authentication.OAuthLibConfig.showDebugInformation=true
sapcxenvconfig.frontend.authentication.OAuthLibConfig.disablePKCE=false
sapcxenvconfig.frontend.authentication.OAuthLibConfig.postLogoutRedirectUri=${ccv2.services.jsapps.url.0}
sapcxenvconfig.frontend.authentication.OAuthLibConfig.customQueryParams.audience=${sapcxsinglesignon.filter.idp.audience}

#-------------------------------------------------------------------
# Optional logging improvements

# Logging configuration for local development
log4j2.logger.sso.name=tools.sapcx.commerce.sso
log4j2.logger.sso.level=DEBUG
